### ISSUE TITLE
Viridescent Venerer resistance shred not accounting for diminishing return

### ISSUE THREAD

**Issue by SiriusGreyhound** [JenShin-368/GenshinImpactCalculator#39]
Someone has reported that the Viridescent Venerer 4-piece bonus increases elemental damage by 40% in all cases, even though any resistance reduction that brings resistance below 0% is halved. So in the case of a Hilichurl with 10% base resistance the result would be -15% resistance: 10% normal and half of the remaining 30%. 

After checking the source code I've definitely found that the VV 4-piece bonus adds 40% elemental damage buff to simulate the effect of the resistance shredding, but the resistance works differently as mentioned above. 

Is there a way to check the resistance of the enemy calc and reduce it accordingly or use conditions based on the enemy resistance to tweak the elemental damage buff?

**Comment by JenShin-368** [comment]
The VV 4-piece bonus does not add 40% elemental damage, it shreds resistance by 40%. Looking at the source code may be misleading because the use of the elemental damage is only to indicate which resistance is being shredded. Resistance is always reduced by 40% but the damage mitigation that results changes depending on whether the enemy's final resistance is under 0%.

I did a quick test to verify and VV does not increase elemental damage by 40% (closer to 60% when res is over 40%) and less when it's less than that.
