### ISSUE TITLE
Summit Shaper Stacks Unclear

### ISSUE THREAD

**Issue by Xanrai** [JenShin-368/GenshinImpactCalculator#8]
Summit Shaper is only able to accrue only up to 5 stacks of its effect, but the calculator's maximum is 10 stacks instead, and should be rectified as soon as possible.

**Comment by JenShin-368** [comment]
This is working as intended. While it can technically have only 5 stacks, the additional effect (while protected by a shield) increases the effect of the stacks by 100%, effectively doubling the number of stacks you can have. Since the calculator currently doesn't have the ability to "increase the effect of a buff by 100%" additional stacks are provided instead.

**Comment by SiriusGreyhound** [comment]
But, perhaps we could rename the stacks so it makes more sense. 
It could go 1-5 Stacks and then it could have 1-5 Stacks (shield) after so it's more obvious.

**Comment by JenShin-368** [comment]
An overhaul of all the descriptions is currently planned to make it more clear how the input fields are being related to the abilities/buffs being toggled or stacked. Hopefully, it will make it more clear what's going on when you check a toggle or use the stacks.

**Comment by SiriusGreyhound** [comment]
This issue is now part of https://github.com/JenShin-368/GenshinImpactCalculator/issues/26
